# **Data Processing**

In [422]:
import pandas as pd
import numpy as np
fp_ds = pd.read_csv('/content/fp_ds.csv')
fp_ds

,x,y,rssa11,rssa12,rssa13,rssa14,rssa15,rssa21,rssa22,rssa23,...,rssa51,rssa52,rssa53,rssa54,rssa55,rssa61,rssa62,rssa63,rssa64,rssa65
0,0,0,-27.0,-30.0,-29.0,-25.0,-23.0,-67.0,-70.0,-68.0,...,-68.0,-71.0,-69.0,-66.0,-64.0,-70.0,-73.0,-72.0,-68.0,-66.0
1,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,0,-55.0,-51.0,-50.0,-50.0,-57.0,-69.0,-65.0,-64.0,...,-69.0,-66.0,-64.0,-64.0,-71.0,-71.0,-67.0,-66.0,-66.0,-73.0
3,3,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,0,-60.0,-60.0,-58.0,-53.0,-55.0,-70.0,-68.0,-66.0,...,-70.0,-69.0,-66.0,-61.0,-63.0,-71.0,-70.0,-67.0,-62.0,-64.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,6,10,-71.0,-62.0,-67.0,-62.0,-64.0,-65.0,-56.0,-62.0,...,-50.0,-41.0,-47.0,-41.0,-44.0,-62.0,-53.0,-58.0,-53.0,-55.0
117,7,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,8,10,-72.0,-68.0,-69.0,-71.0,-65.0,-68.0,-64.0,-65.0,...,-60.0,-56.0,-56.0,-59.0,-53.0,-56.0,-52.0,-53.0,-55.0,-49.0
119,9,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120,10,10,-68.0,-68.0,-69.0,-70.0,-67.0,-65.0,-65.0,-66.0,...,-59.0,-59.0,-60.0,-61.0,-58.0,-27.0,-25.0,-26.0,-27.0,-24.0

***Estimating missing RSSI values (odd rows and columns)***

In [423]:
#Creating  RSSI even super row vectors (each row vector comprises of the vectors of positions of that row)
row0 = fp_ds.loc[fp_ds['x'] == 0]
row0 = row0.drop(columns = ['x','y']);
row0 = row0.values.reshape(-1)

row2 = fp_ds.loc[fp_ds['x'] == 2]
row2 = row2.drop(columns = ['x','y']);
row2 = row2.values.reshape(-1)

row4 = fp_ds.loc[fp_ds['x'] == 4]
row4 = row4.drop(columns = ['x','y']);
row4 = row4.values.reshape(-1)

row6 = fp_ds.loc[fp_ds['x'] == 6]
row6 = row6.drop(columns = ['x','y']);
row6 = row6.values.reshape(-1)

row8 = fp_ds.loc[fp_ds['x'] == 8]
row8 = row8.drop(columns = ['x','y']);
row8 = row8.values.reshape(-1)

row10 = fp_ds.loc[fp_ds['x'] == 10]
row10 = row10.drop(columns = ['x','y']);
row10 = row10.values.reshape(-1)

#Estimating RSSI odd super row vectors 
row1 =(row0+row2)/2
row3 =(row2+row4)/2
row5 =(row4+row6)/2
row7 =(row6+row8)/2
row9 =(row8+row10)/2

row_array = np.stack((row0,row1,row2,row3,row4,row5,row6,row7,row8,row9,row10))
row_array.shape

(11, 330)

In [425]:
#extracting Colunms super vectors

col0 = row_array[:, 0:30]                  
col1 = row_array[:, 30:60]
col2 = row_array[:, 60:90]
col3 = row_array[:, 90:120]
col4 = row_array[:, 120:150]
col5 = row_array[:, 150:180]
col6 = row_array[:, 180:210]
col7 = row_array[:, 210:240]
col8 = row_array[:, 240:270]
col9 = row_array[:, 270:300]
col10 = row_array[:, 300:330]


#Estimating RSSIs corresponding to odd super Colunms vectors 
col1 = (col0+col2)/2
col3 = (col2+col4)/2
col5 = (col4+col6)/2
col7 = (col6+col8)/2
col9 = (col8+col10)/2

final_estimated_fp_ds = np.concatenate((col0,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10), axis=0)

final_estimated_fp_ds

array([[-27. , -30. , -29. , ..., -72. , -68. , -66. ],
       [-41. , -40.5, -39.5, ..., -69. , -67. , -69.5],
       [-55. , -51. , -50. , ..., -66. , -66. , -73. ],
       ...,
       [-72. , -68. , -69. , ..., -53. , -55. , -49. ],
       [-70. , -68. , -69. , ..., -39.5, -41. , -36.5],
       [-68. , -68. , -69. , ..., -26. , -27. , -24. ]])

In [426]:
#extracting column headers(to use later in final_estimated_fp_ds )
column_headers =[]
for col in fp_ds.columns:
  column_headers.append(col)
  
column_headers.remove('x')
column_headers.remove('y')
print(column_headers)

['rssa11', 'rssa12', 'rssa13', 'rssa14', 'rssa15', 'rssa21', 'rssa22', 'rssa23', 'rssa24', 'rssa25', 'rssa31', 'rssa32', 'rssa33', 'rssa34', 'rssa35', 'rssa41', 'rssa42', 'rssa43', 'rssa44', 'rssa45', 'rssa51', 'rssa52', 'rssa53', 'rssa54', 'rssa55', 'rssa61', 'rssa62', 'rssa63', 'rssa64', 'rssa65']

In [427]:
#Converting final_estimated_fp_ds from numpy to DataFrame
final_estimated_fp_ds = pd.DataFrame(final_estimated_fp_ds, columns=column_headers)

#adding corresponding position columns
extracted_col_x = fp_ds['x']
extracted_col_y = fp_ds['y']

final_estimated_fp_ds = final_estimated_fp_ds.join(extracted_col_x)
final_estimated_fp_ds = final_estimated_fp_ds.join(extracted_col_y)

#mapping 2d points to 1d indices  
final_estimated_fp_ds['index'] = range(0, len(final_estimated_fp_ds))
col_index = final_estimated_fp_ds.pop('index')
final_estimated_fp_ds.insert(0, col_index.name, col_index)

final_estimated_fp_ds

,index,rssa11,rssa12,rssa13,rssa14,rssa15,rssa21,rssa22,rssa23,rssa24,...,rssa53,rssa54,rssa55,rssa61,rssa62,rssa63,rssa64,rssa65,x,y
0,0,-27.0,-30.0,-29.0,-25.0,-23.0,-67.0,-70.0,-68.0,-65.0,...,-69.0,-66.0,-64.0,-70.0,-73.0,-72.0,-68.0,-66.0,0,0
1,1,-41.0,-40.5,-39.5,-37.5,-40.0,-68.0,-67.5,-66.0,-64.5,...,-66.5,-65.0,-67.5,-70.5,-70.0,-69.0,-67.0,-69.5,1,0
2,2,-55.0,-51.0,-50.0,-50.0,-57.0,-69.0,-65.0,-64.0,-64.0,...,-64.0,-64.0,-71.0,-71.0,-67.0,-66.0,-66.0,-73.0,2,0
3,3,-57.5,-55.5,-54.0,-51.5,-56.0,-69.5,-66.5,-65.0,-63.0,...,-65.0,-62.5,-67.0,-71.0,-68.5,-66.5,-64.0,-68.5,3,0
4,4,-60.0,-60.0,-58.0,-53.0,-55.0,-70.0,-68.0,-66.0,-62.0,...,-66.0,-61.0,-63.0,-71.0,-70.0,-67.0,-62.0,-64.0,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,116,-71.0,-62.0,-67.0,-62.0,-64.0,-65.0,-56.0,-62.0,-56.0,...,-47.0,-41.0,-44.0,-62.0,-53.0,-58.0,-53.0,-55.0,6,10
117,117,-71.5,-65.0,-68.0,-66.5,-64.5,-66.5,-60.0,-63.5,-61.5,...,-51.5,-50.0,-48.5,-59.0,-52.5,-55.5,-54.0,-52.0,7,10
118,118,-72.0,-68.0,-69.0,-71.0,-65.0,-68.0,-64.0,-65.0,-67.0,...,-56.0,-59.0,-53.0,-56.0,-52.0,-53.0,-55.0,-49.0,8,10
119,119,-70.0,-68.0,-69.0,-70.5,-66.0,-66.5,-64.5,-65.5,-67.0,...,-58.0,-60.0,-55.5,-41.5,-38.5,-39.5,-41.0,-36.5,9,10
120,120,-68.0,-68.0,-69.0,-70.0,-67.0,-65.0,-65.0,-66.0,-67.0,...,-60.0,-61.0,-58.0,-27.0,-25.0,-26.0,-27.0,-24.0,10,10

***Creating the final Fingerprint Dataset***

In [428]:
#converting RSSI vector of positions with dimentionality of 1*30 to vectors of 1*6 by performing max or mean or min based on the chosen flag 
max = False
mean = True
min = False
if(max == True):
  final_estimated_fp_ds['rssa1'] = final_estimated_fp_ds[['rssa11','rssa12','rssa13','rssa14','rssa15',]].max(axis=1)
  final_estimated_fp_ds['rssa2'] = final_estimated_fp_ds[['rssa21','rssa22','rssa23','rssa24','rssa25',]].max(axis=1)
  final_estimated_fp_ds['rssa3'] = final_estimated_fp_ds[['rssa31','rssa32','rssa33','rssa34','rssa35',]].max(axis=1)
  final_estimated_fp_ds['rssa4'] = final_estimated_fp_ds[['rssa41','rssa42','rssa43','rssa44','rssa45',]].max(axis=1)
  final_estimated_fp_ds['rssa5'] = final_estimated_fp_ds[['rssa51','rssa52','rssa53','rssa54','rssa55',]].max(axis=1)
  final_estimated_fp_ds['rssa6'] = final_estimated_fp_ds[['rssa61','rssa62','rssa63','rssa64','rssa65',]].max(axis=1)
  final_estimated_fp_ds_new = final_estimated_fp_ds.drop(columns=['rssa11','rssa12','rssa13','rssa14','rssa15','rssa61','rssa21','rssa22','rssa23','rssa24','rssa25','rssa31','rssa32','rssa33','rssa34','rssa35','rssa41','rssa42','rssa43','rssa44','rssa45','rssa51','rssa52','rssa53','rssa54','rssa55','rssa62','rssa63','rssa64','rssa65'])
if(mean == True):
  final_estimated_fp_ds['rssa1'] = final_estimated_fp_ds[['rssa11','rssa12','rssa13','rssa14','rssa15',]].mean(axis=1)
  final_estimated_fp_ds['rssa2'] = final_estimated_fp_ds[['rssa21','rssa22','rssa23','rssa24','rssa25',]].mean(axis=1)
  final_estimated_fp_ds['rssa3'] = final_estimated_fp_ds[['rssa31','rssa32','rssa33','rssa34','rssa35',]].mean(axis=1)
  final_estimated_fp_ds['rssa4'] = final_estimated_fp_ds[['rssa41','rssa42','rssa43','rssa44','rssa45',]].mean(axis=1)
  final_estimated_fp_ds['rssa5'] = final_estimated_fp_ds[['rssa51','rssa52','rssa53','rssa54','rssa55',]].mean(axis=1)
  final_estimated_fp_ds['rssa6'] = final_estimated_fp_ds[['rssa61','rssa62','rssa63','rssa64','rssa65',]].mean(axis=1)
  final_estimated_fp_ds_new = final_estimated_fp_ds.drop(columns=['rssa11','rssa12','rssa13','rssa14','rssa15','rssa61','rssa21','rssa22','rssa23','rssa24','rssa25','rssa31','rssa32','rssa33','rssa34','rssa35','rssa41','rssa42','rssa43','rssa44','rssa45','rssa51','rssa52','rssa53','rssa54','rssa55','rssa62','rssa63','rssa64','rssa65'])

if(min == True):
  final_estimated_fp_ds['rssa1'] = final_estimated_fp_ds[['rssa11','rssa12','rssa13','rssa14','rssa15',]].min(axis=1)
  final_estimated_fp_ds['rssa2'] = final_estimated_fp_ds[['rssa21','rssa22','rssa23','rssa24','rssa25',]].min(axis=1)
  final_estimated_fp_ds['rssa3'] = final_estimated_fp_ds[['rssa31','rssa32','rssa33','rssa34','rssa35',]].min(axis=1)
  final_estimated_fp_ds['rssa4'] = final_estimated_fp_ds[['rssa41','rssa42','rssa43','rssa44','rssa45',]].min(axis=1)
  final_estimated_fp_ds['rssa5'] = final_estimated_fp_ds[['rssa51','rssa52','rssa53','rssa54','rssa55',]].min(axis=1)
  final_estimated_fp_ds['rssa6'] = final_estimated_fp_ds[['rssa61','rssa62','rssa63','rssa64','rssa65',]].min(axis=1)
  final_estimated_fp_ds_new = final_estimated_fp_ds.drop(columns=['rssa11','rssa12','rssa13','rssa14','rssa15','rssa61','rssa21','rssa22','rssa23','rssa24','rssa25','rssa31','rssa32','rssa33','rssa34','rssa35','rssa41','rssa42','rssa43','rssa44','rssa45','rssa51','rssa52','rssa53','rssa54','rssa55','rssa62','rssa63','rssa64','rssa65'])

final_estimated_fp_ds_new

     index   x   y  rssa1  rssa2  rssa3  rssa4  rssa5  rssa6
0        0   0   0  -26.8  -66.6  -61.0  -66.8  -67.6  -69.8
1        1   1   0  -39.7  -66.6  -58.5  -65.9  -67.2  -69.2
2        2   2   0  -52.6  -66.6  -56.0  -65.0  -66.8  -68.6
3        3   3   0  -54.9  -66.3  -51.3  -63.1  -66.3  -67.7
4        4   4   0  -57.2  -66.0  -46.6  -61.2  -65.8  -66.8
..     ...  ..  ..    ...    ...    ...    ...    ...    ...
116    116   6  10  -65.2  -59.6  -64.0  -64.6  -44.6  -56.2
117    117   7  10  -67.1  -62.3  -66.0  -66.1  -50.7  -54.6
118    118   8  10  -69.0  -65.0  -68.0  -67.6  -56.8  -53.0
119    119   9  10  -68.7  -65.2  -67.2  -66.5  -58.1  -39.4
120    120  10  10  -68.4  -65.4  -66.4  -65.4  -59.4  -25.8

[121 rows x 9 columns]

# **Positioning Dory**

In [429]:
X = final_estimated_fp_ds_new.drop(columns = ['x','y', 'index']);
X = X.to_numpy()
#X.shape

In [430]:
#Computing cosine similarity between Dory's RSSI vector and the fingerprint dataset
from sklearn.metrics.pairwise import cosine_similarity
dory_rssi = [-57,-63,-58,-64,-63,-66]
similarity = []
for i in range(0,len(X)):
  similarity.append(cosine_similarity([X[i]], [dory_rssi]))
similarity

max_index = np.argmax(similarity)
pos_x = final_estimated_fp_ds_new.loc[final_estimated_fp_ds_new['index'] == max_index ,'x'].values[0]
pos_y = final_estimated_fp_ds_new.loc[final_estimated_fp_ds_new['index'] == max_index ,'y'].values[0]
result =(pos_x , pos_y)
print("Dory's position: ",result)

Dory's position:  (2, 3)

In [431]:
from google.colab import files

final_estimated_fp_ds.to_csv('final_estimated_fp_ds.csv', encoding = 'utf-8-sig') 
files.download('final_estimated_fp_ds.csv')
final_estimated_fp_ds_new.to_csv('final_estimated_fp_ds_new.csv', encoding = 'utf-8-sig') 
files.download('final_estimated_fp_ds_new.csv')